WebAppMVC/Controllers/CartController.cs
using Braintree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using WebApp_DataAccess.Data;
using WebApp_DataAccess.Repository;
using WebApp_DataAccess.Repository.IRepository;
using WebApp_Models;
using WebApp_Utility.BrainTree;
using WebAppMVC_Models;
using WebAppMVC_Models.ViewModels;
using WebAppMVC_Utility;

namespace WebAppMVC.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;

        private readonly IProductRepository productRepository;
        private readonly IApplicationUserRepository applicationUserRepository;
        private readonly IOrderTableRepository orderTableRepository;
        private readonly IOrderLineRepository orderLineRepository;

        private readonly ISalesTableRepository salesTableRepository;
        private readonly ISalesLineRepository salesLineRepository;
        private readonly IBrainTreeGate brainTreeGate;

        [BindProperty]
        public ProductUserViewModel? ProductUserViewModel { get; set; }


        public CartController(IApplicationUserRepository applicationUserRepository, IProductRepository productRepository,
                              IWebHostEnvironment webHostEnvironment, IEmailSender emailSender,
                              IOrderTableRepository orderTableRepository, IOrderLineRepository orderLineRepository,
                              ISalesTableRepository salesTableRepository, ISalesLineRepository salesLineRepository,
                              IBrainTreeGate brainTreeGate
                              )
        {
            this._webHostEnvironment = webHostEnvironment;
            this._emailSender = emailSender;
            this.productRepository = productRepository;
            this.applicationUserRepository = applicationUserRepository;
            this.orderTableRepository = orderTableRepository;
            this.orderLineRepository = orderLineRepository;
            this.salesTableRepository = salesTableRepository;
            this.salesLineRepository = salesLineRepository;
            this.brainTreeGate = brainTreeGate;
        }
//------------------------------//------------------------------//------------------------------//------------------------------//------------------------------
        public IActionResult Index() // GET
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            IEnumerable<ShoppingCart> enumeratorShoppingCart = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);

            if (enumeratorShoppingCart != null && enumeratorShoppingCart.Any())
            {
                shoppingCartList = (List<ShoppingCart>)enumeratorShoppingCart;
            }

            List<int> prodInCart = shoppingCartList.Select(p => p.ProductId).ToList();
            IEnumerable<ProductModel> prodList = productRepository.GetAll(p => prodInCart.Contains(p.Id));

            foreach (ProductModel prod in prodList)
            {
                var ___ = shoppingCartList.Where(p => p.ProductId == prod.Id).FirstOrDefault();
                prod.TempQty = ___ != null ? ___.Qty : 0;
            }

            return View(prodList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult Index(IEnumerable<ProductModel> products) //POST
        {
            var shoppingCart = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);

            foreach (var i in products)
            {
                var s = shoppingCart.Where(c => c.ProductId == i.Id).FirstOrDefault();
                s.Qty = i.TempQty;
            }

            HttpContext.Session.Set(WC.SessionCart, shoppingCart);
            return RedirectToAction(nameof(Summary));
        }


//------------------------------//------------------------------//------------------------------//------------------------------//------------------------------
        public IActionResult Remove(int id)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            IEnumerable<ShoppingCart> enumeratorShoppingCart = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);

            if (enumeratorShoppingCart != null && enumeratorShoppingCart.Any())
            {
                shoppingCartList = (List<ShoppingCart>)enumeratorShoppingCart;
            }

            shoppingCartList.Remove(shoppingCartList.FirstOrDefault(a => a.ProductId == id));

            List<int> prodInCart = shoppingCartList.Select(p => p.ProductId).ToList();
            IEnumerable<ProductModel> prodList = productRepository.GetAll(p => prodInCart.Contains(p.Id));
            
            HttpContext.Session.Set( WC.SessionCart, shoppingCartList );

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Summary() //GET
        {
            var claims = (ClaimsIdentity)User.Identity;
            var claim = claims.FindFirst(ClaimTypes.NameIdentifier);
            var userName = User.FindFirstValue(ClaimTypes.Name);

            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>(); 
            IEnumerable<ShoppingCart> enumeratorShoppingCart = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);

            int isSessionOrderId=0;
            var key = HttpContext.Session.Keys.Where(s => s == WC.SessionOrderId);
            var key1 = key.ToList();
            var keyAny = key.Any();

            if (HttpContext.Session.Keys.Where(s => s == WC.SessionOrderId).Any())
                isSessionOrderId = HttpContext.Session.Get<int>(WC.SessionOrderId);

            if (enumeratorShoppingCart != null && enumeratorShoppingCart.Any())
            {
                shoppingCartList = (List<ShoppingCart>)enumeratorShoppingCart;
            }

            List<int> prodInCart = shoppingCartList.Select(p => p.ProductId).ToList();
            IEnumerable<ProductModel> prodList = productRepository.GetAll(p => prodInCart.Contains(p.Id));

            ProductUserViewModel = new ProductUserViewModel();
            ProductUserViewModel.ApplicationUser = applicationUserRepository.FirstOrDefault(q => q.Id == claim.Value);

            foreach (var i in prodList)
            {
                i.TempQty = shoppingCartList.Where(c => c.ProductId == i.Id).FirstOrDefault().Qty;
            }
            ProductUserViewModel.ProductList = prodList.ToList();
            

            if (User.IsInRole(WC.AdminRole))
            {
                if (isSessionOrderId == 0)
                {
                    ProductUserViewModel.ApplicationUser.FullName = "";
                    ProductUserViewModel.ApplicationUser.PhoneNumber = "";
                    ProductUserViewModel.ApplicationUser.Email = "";
                }

                var gateway = brainTreeGate.GetGateway();
                var clientToken = gateway.ClientToken.Generate();
                ViewBag.ClientToken = clientToken;
            }
            return View(ProductUserViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(IFormCollection collection, ProductUserViewModel productUserViewModel)
        {
            var claims = (ClaimsIdentity)User.Identity;
            var claims_1 = User.Identity;
            var claim = claims.FindFirst(ClaimTypes.NameIdentifier);
            var user_nameIdentifier = User.FindFirstValue(ClaimTypes.NameIdentifier);
            
            if (User.IsInRole(WC.AdminRole))
            {
                double finalOrderTotal = productUserViewModel.ProductList.Sum(i => i.Price * i.TempQty);

                SalesTable salesTable = new SalesTable()
                {
                    CreatedBy = applicationUserRepository.FirstOrDefault(filter: q => q.Id == user_nameIdentifier),
                    CreatedByUserId = claim.Value,
                    FinalOrderTotal = finalOrderTotal,
                    PhoneNumber = productUserViewModel.ApplicationUser.PhoneNumber,
                    StreetAddress = productUserViewModel.ApplicationUser.StreetAddress,
                    City = productUserViewModel.ApplicationUser.City,
                    State = productUserViewModel.ApplicationUser.State,
                    PostalCode = productUserViewModel.ApplicationUser.PostalCode,
                    FullName = productUserViewModel.ApplicationUser.FullName,
                    Email = productUserViewModel.ApplicationUser.Email,
                    OrderDate = DateTime.Now,
                    OrderStatus = WC.StatusPending,
                };

                salesTableRepository.Add(salesTable);
                salesTableRepository.Save();

                foreach (var i in productUserViewModel.ProductList)
                {
                    SalesLine salesLine = new SalesLine()
                    {
                        SalesTable = salesTable,
                        ProductId = i.Id,
                        Qty = i.TempQty,
                        Price = i.Price,
                    };
                    salesLineRepository.Add(salesLine);
                }
                salesLineRepository.Save();



                string nonceFromTheClient = collection["payment_method_nonce"];

                var request = new TransactionRequest
                {
                    Amount = Convert.ToDecimal(finalOrderTotal),
                    PaymentMethodNonce = nonceFromTheClient,
                    OrderId = salesTable.Id.ToString(),
                    Options = new TransactionOptionsRequest
                    {
                        SubmitForSettlement = true
                    }

WebAppMVC/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using WebApp_DataAccess.Data;
using WebApp_DataAccess.Repository.IRepository;
using WebAppMVC_Models;
using WebAppMVC_Utility;

namespace WebAppMVC.Controllers
{
    [Authorize(Roles=WC.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<CategoryModel> objList = categoryRepository.GetAll();
            return View(objList);
        }

//---------------------------------------------------------------------------------------------------
        
        //GET - для CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST - для CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryModel obj)
        {
            if (ModelState.IsValid)
            {
                categoryRepository.Add(obj);
                categoryRepository.Save();
                TempData[WC.Success] = "Операция выполнена успешно!";
                return RedirectToAction("Index");
            }

            TempData[WC.Error] = "Ошибка создания категории!";
            return View(obj);   
        }

//---------------------------------------------------------------------------------------------------

        //GET - для EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = categoryRepository.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - для EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryModel obj)
        {
            if (ModelState.IsValid)
            {
                categoryRepository.Update(obj);
                categoryRepository.Save();
                TempData[WC.Success] = "Операция выполнена успешно!";
                return RedirectToAction("Index");
            }
            return View(obj);   
        }

//---------------------------------------------------------------------------------------------------

        //GET - для DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = categoryRepository.Find(id.GetValueOrDefault());
            if (obj == null) 
            { 
                return NotFound();
            }

            return View(obj);
        }

        //POST - для DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = categoryRepository.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            categoryRepository.Remove(obj);
            categoryRepository.Save();
            TempData[WC.Success] = "Операция выполнена успешно!";
            return RedirectToAction("Index");
        }

//---------------------------------------------------------------------------------------------------


    }
}

WebAppMVC/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using WebApp_DataAccess.Repository;
using WebApp_DataAccess.Repository.IRepository;
using WebAppMVC_Models;

namespace WebAppMVC.Controllers
{

    [Authorize]
    public class ChatController : Controller
    {
        readonly IApplicationUserRepository applicationUserRepository;
        readonly IChatRepository chatRepository;

        public ChatController(IApplicationUserRepository applicationUserRepository, IChatRepository chatRepository)
        {
            this.applicationUserRepository = applicationUserRepository;
            this.chatRepository = chatRepository;
        }

        public IActionResult Index()
        {
            var userClaim = User.Claims.FirstOrDefault();
            var user = applicationUserRepository.FirstOrDefault(q => q.Id == userClaim.Value);


            return View(user);
        }

        public IActionResult Chat_New()
        {
            var userClaim = User.Claims.FirstOrDefault();
            var user = applicationUserRepository.FirstOrDefault(q => q.Id == userClaim.Value);
            

            return View(user);
        }



    }
}

WebAppMVC/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using WebApp_DataAccess.Repository;
using WebApp_DataAccess.Repository.IRepository;
using WebApp_Models;
using WebApp_Models.ViewModels;
using WebAppMVC_Models;
using WebAppMVC_Utility;

namespace WebAppMVC.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        IOrderTableRepository orderTableRepository;
        IOrderLineRepository orderLineRepository;

        public OrderController(IOrderTableRepository orderTableRepository, IOrderLineRepository orderLineRepository)
        {
            this.orderTableRepository = orderTableRepository;
            this.orderLineRepository = orderLineRepository;
        }

        [Authorize(Roles = WC.AdminRole)]
        public IActionResult Index()
        {
            IEnumerable<OrderTable> ot = orderTableRepository.GetAll();

            return View(ot);
        }

        public IActionResult Details( int? id )
        {
            OrderVM orderVM = new OrderVM();
            
            orderVM.orderTable = orderTableRepository.Find(id ?? 0);
            orderVM.orderLine_Enumerator = orderLineRepository.GetAll(l => l.OrderId == id, includeProperties:"Product");

            return View(orderVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(OrderVM order)
        { 
            OrderVM orderVM = new OrderVM();
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            
            orderVM.orderTable = orderTableRepository.Find(order.orderTable.Id);

            foreach (var i in orderLineRepository.GetAll(l => l.OrderId == orderVM.orderTable.Id))
            {
                ShoppingCart shoppingCart = new ShoppingCart();
                shoppingCart.ProductId = i.ProductId;
                shoppingCartList.Add(shoppingCart);
            }
            HttpContext.Session.Clear();
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);
            HttpContext.Session.Set<int>(WC.SessionOrderId, order.orderTable.Id);

            return RedirectToAction("Index", "Cart");
        }

        [HttpPost]
        public IActionResult Delete(OrderVM order)
        {
            var orderTable = orderTableRepository.Find(order.orderTable.Id);
            var orderLineRange = orderLineRepository.GetAll(filter: l => l.OrderId == orderTable.Id);

            orderTableRepository.Remove(orderTable);
            orderLineRepository.RemoveRange(orderLineRange);

            orderTableRepository.Save();
            orderLineRepository.Save();

            return RedirectToAction(nameof(Index));
        }


        #region API CALLS
        [HttpGet]
        public IActionResult GetOrdersList()
        {
            var ot = orderTableRepository.GetAll();
            JsonResult o = Json(ot);

            var ret = Json(new { data = ot });
            return ret;
        }
        #endregion
    }
}

WebAppMVC/Views/Shared/_IndividualProductCard.cshtml
@model WebAppMVC_Models.ProductModel
@using WebAppMVC_Utility;



<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@String.Format("{0:c0}", Model.Price) / шт.</span></label> </div>
        </div>

        <img src="@WC.ImagePath@Model.Image" class="card-img img-fluid rounded shadow mx-auto d-block" />



        <div class="card-body  px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100" style="background-color:palevioletred">@Model.Category.Name</span>
            </div>

            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesc</p>
            </div>
            <div class="col-12 p-1">
                <a class="btn btn-success form-control btn-sm p-2" style="height:40px" asp-controller="Home" asp-route-Id="@Model.Id" asp-action="Details">View Details</a>
            </div>
        </div>
    </div>
</div>
 


@{
    //this.Write("End of file : _IndividualProductCard.cshtml");
}

WebAppMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using WebAppMVC_Utility

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebAppMVC</title>

	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/WebAppMVC.styles.css" asp-append-version="true" />

	<!--sweetalert2.github.io-->
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<!--sweetalert2.github.io-->
	<!--SUMMERNOTE WORKED 100%-->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote-bs4.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote-bs4.min.js"></script>
	<!--SUMMERNOTE WORKED 100%-->
	<!--Загружается долго  https://datatables.net/  -->
	<link rel="stylesheet" href="//cdn.datatables.net/2.3.4/css/dataTables.dataTables.min.css" />
	<script src="//cdn.datatables.net/2.3.4/js/dataTables.min.js"></script>
	<!--Загружается долго  https://datatables.net/  -->
	<!--TOASTR-->
	<!--
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
	-->
	<!--TOASTR-->
	<!--BOOTSTRAP-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
	<!--BOOTSTRAP-->
	<!--BOOTSTRAP ICONS-->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
	<!--BOOTSTRAP ICONS-->
	<!-- Syncfusion ASP.NET Core controls styles -->
	<link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/31.2.2/fluent.css" />
	<!-- Syncfusion ASP.NET Core controls scripts -->
	<script src="https://cdn.syncfusion.com/ej2/31.2.2/dist/ej2.min.js"></script>



	<!-- SIGNALR -->
	<script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>


</head>








<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-gradient border-bottom box-shadow mb-3">
			<div class="container-fluid">

				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">-=My Site (home)=-</a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
						aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">


					<ul class="navbar-nav flex-grow-1">

						<li class="nav-item">
							<a class="nav-link text-danger bg-light" asp-area="" asp-controller="Home" asp-action="Shop">Магазин</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-danger bg-light" asp-area="" asp-controller="MyDailyJournal" asp-action="Index">Ежедневник</a>
						</li>

						<li class="nav-item">
							<a class="nav-link text-danger bg-light" asp-area="" asp-controller="Chat" asp-action="Index">Чат</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-danger bg-light" asp-area="" asp-controller="Chat" asp-action="Chat_New">Чат(new)</a>
						</li>

						@if (User.IsInRole(WC.AdminRole))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Редактор магазина
								</a>
								<ul class="dropdown-menu">
									<a class="dropdown-item text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
									<a class="dropdown-item text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item text-dark" asp-area="Identity" asp-page="/Account/Register"> Create Admin User</a>
								</ul>
							</li>

							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Управление магазином
								</a>
								<ul class="dropdown-menu">
									<a class="dropdown-item text-dark" asp-area="" asp-controller="Order" asp-action="Index">Ордера(Order)</a>
									<a class="dropdown-item text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Заказы(Sales)</a>
								</ul>
							</li>
						}

						<li>
							@if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) != null)
							{
								<a asp-action="Index" asp-controller="Cart" class="nav-link">
									@{
										var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;
									}
									<i>(В корзине: @count)</i>
								</a>
							}
							else
							{
								<a href="#" class="nav-link">
									<i>(В корзине пусто!)</i>
								</a>
							}
						</li>


					</ul>
					<partial name="_LoginPartial" />

				</div>
			</div>
		</nav>
	</header>


	<!-- BOOTSRAP TOAST -->
	<div id="toastContainer" class="position-fixed top-0 start-50 translate-middle-x mt-3" style="z-index: 1055;">
		<div id="centerToast" class="toast align-items-center text-bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
			<div class="d-flex">
				<div class="toast-body">
					Успешно!
				</div>
				<button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Закрыть"></button>
			</div>
		</div>
	</div>

	<script>
		function showToast(message, type = 'success', delay = 3000) {
			const toastEl = document.getElementById('centerToast');

			if (!toastEl) {
				console.error("Toast элемент не найден!");
				return;
			}

			// Меняем текст и цвет
			const bodyEl = toastEl.querySelector('.toast-body');
			if (bodyEl) bodyEl.textContent = message;

			toastEl.className = `toast align-items-center text-bg-${type} border-0`;

			// Создаём и показываем toast
			const toast = new bootstrap.Toast(toastEl, { delay: delay, autohide: true });
			toast.show();
		}
	</script>
	<!-- BOOTSRAP TOAST -->



	<main role="main" class="pb-3">
		<partial name="_Notifications" />
		@RenderBody()
	</main>

	<footer class="border-top footer text-muted">
	</footer>

	<ejs-scripts></ejs-scripts>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppMVC/Views/Shared/_Notifications.cshtml
@using WebAppMVC_Utility

@if (TempData[WC.Success] != null)
{
	<!--TOASTR-->
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
	<!--TOASTR-->
	<script type="text/javascript">
		toastr.success('@TempData[WC.Success]');	
	</script>
}

@if (TempData[WC.Error] != null)
{
	<!--TOASTR-->
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
	<!--TOASTR-->
	<script type="text/javascript">
		toastr.error('@TempData[WC.Error]');
	</script>
}